DROP INDEX idx_t1 ON shidx_t1;
DROP TABLE shidx_t1;

CREATE TABLE shidx_t1(KEY STRING, VALUE STRING);

CREATE INDEX idx_t1 ON TABLE shidx_t1(KEY) AS "COMPACT" WITH DEFERRED REBUILD;
ALTER INDEX idx_t1 ON shidx_t1 REBUILD;

EXPLAIN
SHOW INDEX IN shidx_t1;

SHOW INDEX IN shidx_t1;

EXPLAIN
SHOW INDEXES IN shidx_t1;

SHOW INDEXES IN shidx_t1;

EXPLAIN
SHOW INDEX FROM shidx_t1;

SHOW INDEX FROM shidx_t1;

EXPLAIN
SHOW INDEXES FROM shidx_t1;

SHOW INDEXES FROM shidx_t1;

DROP INDEX idx_t1 ON shidx_t1;
DROP TABLE shidx_t1;
